#!/usr/bin/env node
/**
 * Non-destructively reconcile the auth-facing contract of an existing Zitadel instance
 * against zitadel/project/pipod-project.json (project flags, project roles, OIDC apps).
 *
 * This script deliberately has no remove operation. --check is the default; --apply
 * only creates resources and updates representations. Client ids are generated by
 * Zitadel; after apply the script prints the project id (the API audience) and the
 * client id of every app.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const TIMEOUT_DEFAULT_MS = 10_000;
const LOOPBACK_HOSTS = new Set(["127.0.0.1", "localhost", "[::1]", "::1"]);

const contractPath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../project/pipod-project.json",
);
const contract = JSON.parse(fs.readFileSync(contractPath, "utf8"));
const desiredProject = contract.project;
const desiredRoles = contract.roles;
const desiredApps = contract.apps;

function configuration(argv = process.argv.slice(2), env = process.env) {
  let mode = "check";
  for (const argument of argv) {
    if (argument === "--check") mode = "check";
    else if (argument === "--apply") mode = "apply";
    else throw new Error(`unknown argument ${JSON.stringify(argument)} (expected --check or --apply)`);
  }
  if (argv.includes("--check") && argv.includes("--apply")) {
    throw new Error("--check and --apply are mutually exclusive");
  }

  const expectedIssuer = required(env.ZITADEL_EXPECTED_ISSUER, "ZITADEL_EXPECTED_ISSUER");
  const pat = required(env.ZITADEL_PAT, "ZITADEL_PAT");

  const issuerUrl = validateSecureUrl(expectedIssuer, "ZITADEL_EXPECTED_ISSUER");
  if (issuerUrl.search || issuerUrl.hash || issuerUrl.username || issuerUrl.password) {
    throw new Error("ZITADEL_EXPECTED_ISSUER must not contain credentials, a query, or a fragment");
  }
  if (issuerUrl.pathname !== "/" && issuerUrl.pathname !== "") {
    throw new Error("ZITADEL_EXPECTED_ISSUER must be the instance origin without a path");
  }
  const issuer = `${issuerUrl.origin}`;
  if (env.ZITADEL_URL) {
    const configuredBase = validateSecureUrl(env.ZITADEL_URL.trim(), "ZITADEL_URL");
    const normalizedBase = `${configuredBase.origin}${configuredBase.pathname.replace(/\/$/, "")}`;
    if (configuredBase.search || configuredBase.hash || normalizedBase !== issuer) {
      throw new Error("ZITADEL_URL does not exactly match ZITADEL_EXPECTED_ISSUER");
    }
  }

  const timeoutMs = Number(env.ZITADEL_HTTP_TIMEOUT_MS ?? TIMEOUT_DEFAULT_MS);
  if (!Number.isInteger(timeoutMs) || timeoutMs < 1_000 || timeoutMs > 30_000) {
    throw new Error("ZITADEL_HTTP_TIMEOUT_MS must be an integer from 1000 through 30000");
  }

  return {
    mode,
    expectedIssuer: issuer,
    projectName: env.ZITADEL_PROJECT?.trim() || "pipod",
    pat,
    origin: issuerUrl.origin,
    timeoutMs,
  };
}

function required(value, name) {
  const trimmed = value?.trim();
  if (!trimmed) throw new Error(`${name} is required as an explicit target confirmation`);
  return trimmed;
}

function validateSecureUrl(value, label) {
  let url;
  try {
    url = new URL(value);
  } catch {
    throw new Error(`${label} is not a valid absolute URL`);
  }
  const loopback = LOOPBACK_HOSTS.has(url.hostname);
  if (url.protocol !== "https:" && !(url.protocol === "http:" && loopback)) {
    throw new Error(`${label} must use HTTPS (HTTP is allowed only for explicit loopback development)`);
  }
  return url;
}

async function request(config, url, options, label) {
  const target = url instanceof URL ? url : new URL(url);
  validateEndpoint(config, target, label);
  let response;
  try {
    response = await fetch(target, {
      ...options,
      redirect: "manual",
      signal: AbortSignal.timeout(config.timeoutMs),
    });
  } catch (error) {
    const reason = error instanceof Error && error.name === "TimeoutError" ? "timed out" : "request failed";
    throw new Error(`${label}: ${reason}`);
  }
  if (response.status >= 300 && response.status < 400) {
    throw new Error(`${label}: redirects are forbidden (HTTP ${response.status})`);
  }
  return response;
}

function validateEndpoint(config, url, label) {
  validateSecureUrl(url.href, label);
  if (url.origin !== config.origin) throw new Error(`${label} is cross-origin`);
  if (url.username || url.password || url.hash) throw new Error(`${label} contains forbidden URL components`);
}

async function jsonResponse(config, url, options, label, expectedStatuses = [200]) {
  const response = await request(config, url, options, label);
  if (!expectedStatuses.includes(response.status)) {
    throw new Error(`${label}: unexpected HTTP ${response.status}`);
  }
  if (response.status === 204) return null;
  const text = await response.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    throw new Error(`${label}: response was not valid JSON`);
  }
}

async function discover(config) {
  const discoveryUrl = new URL(`${config.expectedIssuer}/.well-known/openid-configuration`);
  const document = await jsonResponse(config, discoveryUrl, { method: "GET" }, "instance discovery");
  if (!document || typeof document !== "object") throw new Error("instance discovery was not an object");
  if (document.issuer !== config.expectedIssuer) {
    throw new Error("instance discovery issuer did not exactly match expected issuer");
  }
  for (const [key, value] of Object.entries(document)) {
    if (typeof value === "string" && (key.endsWith("_endpoint") || key.endsWith("_uri"))) {
      let url;
      try {
        url = new URL(value);
      } catch {
        throw new Error(`instance discovery ${key} is not an absolute URL`);
      }
      validateEndpoint(config, url, `instance discovery ${key}`);
    }
  }
  return document;
}

async function api(config, method, apiPath, body, expectedStatuses = [200]) {
  if (!new Set(["GET", "POST", "PUT"]).has(method)) throw new Error(`forbidden management API method ${method}`);
  const headers = { authorization: `Bearer ${config.pat}`, accept: "application/json" };
  if (body !== undefined) headers["content-type"] = "application/json";
  return jsonResponse(
    config,
    new URL(`${config.expectedIssuer}${apiPath}`),
    { method, headers, body: body === undefined ? undefined : JSON.stringify(body) },
    `${method} ${apiPath}`,
    expectedStatuses,
  );
}

async function authenticate(config) {
  await discover(config);
  const me = await api(config, "GET", "/auth/v1/users/me");
  if (!me?.user?.id) throw new Error("ZITADEL_PAT authentication did not resolve a service user");
}

async function readState(config) {
  const search = await api(config, "POST", "/management/v1/projects/_search", {
    queries: [{ nameQuery: { name: config.projectName, method: "TEXT_QUERY_METHOD_EQUALS" } }],
  });
  const projects = (search?.result ?? []).filter((row) => row.name === config.projectName);

  let roles = [];
  let apps = [];
  if (projects.length === 1) {
    const projectId = projects[0].id;
    const roleSearch = await api(config, "POST", `/management/v1/projects/${projectId}/roles/_search`, {
      query: { limit: 200 },
    });
    roles = roleSearch?.result ?? [];
    const appSearch = await api(config, "POST", `/management/v1/projects/${projectId}/apps/_search`, {
      query: { limit: 200 },
    });
    apps = appSearch?.result ?? [];
  }

  const appsByName = new Map();
  for (const app of apps) {
    const rows = appsByName.get(app.name) ?? [];
    rows.push(app);
    appsByName.set(app.name, rows);
  }
  const rolesByKey = new Map();
  for (const role of roles) {
    const key = role.key ?? role.roleKey;
    const rows = rolesByKey.get(key) ?? [];
    rows.push(role);
    rolesByKey.set(key, rows);
  }
  return { projects, roles, apps, appsByName, rolesByKey };
}

function driftFor(state) {
  const drift = [];
  if (state.projects.length !== 1) {
    drift.push(`project ${desiredProject.name} must exist exactly once (found ${state.projects.length})`);
    return drift;
  }
  compareRepresentation(`project ${desiredProject.name}`, state.projects[0], desiredProject, drift);

  for (const role of desiredRoles) {
    const count = state.rolesByKey.get(role.key)?.length ?? 0;
    if (count !== 1) drift.push(`project role ${role.key} must exist exactly once (found ${count})`);
  }

  for (const desired of desiredApps) {
    const rows = state.appsByName.get(desired.name) ?? [];
    if (rows.length !== 1) {
      drift.push(`app ${desired.name} must exist exactly once (found ${rows.length})`);
      continue;
    }
    const { name: _name, ...oidc } = desired;
    compareRepresentation(`app ${desired.name}`, rows[0].oidcConfig ?? {}, oidc, drift);
  }
  return drift;
}

function compareRepresentation(label, actual, expected, drift, fieldPath = "") {
  for (const [key, value] of Object.entries(expected)) {
    const field = fieldPath ? `${fieldPath}.${key}` : key;
    const actualValue = actual?.[key];
    if (Array.isArray(value)) {
      if (!sameStringSet(actualValue, value)) drift.push(`${label} ${field} differs`);
    } else if (value && typeof value === "object") {
      compareRepresentation(label, actualValue ?? {}, value, drift, field);
    } else if (actualValue !== value) {
      // Zitadel omits false/empty booleans from search representations.
      if (value === false && (actualValue === undefined || actualValue === null)) continue;
      drift.push(`${label} ${field} must be ${JSON.stringify(value)}`);
    }
  }
}

function sameStringSet(actual, expected) {
  return (
    Array.isArray(actual) &&
    actual.length === expected.length &&
    [...actual].sort().every((value, index) => value === [...expected].sort()[index])
  );
}

function applyBlockers(state) {
  const blockers = [];
  if (state.projects.length > 1) blockers.push(`duplicate project ${desiredProject.name}`);
  for (const [key, rows] of state.rolesByKey) {
    if (rows.length > 1) blockers.push(`duplicate project role ${key}`);
  }
  for (const [name, rows] of state.appsByName) {
    if (rows.length > 1 && desiredApps.some((app) => app.name === name)) {
      blockers.push(`duplicate app ${name}`);
    }
  }
  return blockers;
}

function matchesRepresentation(actual, desired) {
  const drift = [];
  compareRepresentation("representation", actual, desired, drift);
  return drift.length === 0;
}

function applied(message) {
  process.stdout.write(`applied: ${message}\n`);
}

async function apply(config, initialState) {
  const blockers = applyBlockers(initialState);
  if (blockers.length > 0) {
    throw new Error(`apply refused because non-destructive reconciliation cannot repair:\n- ${blockers.join("\n- ")}`);
  }
  let state = initialState;

  if (state.projects.length === 0) {
    await api(config, "POST", "/management/v1/projects", { ...desiredProject }, [200, 201]);
    applied(`created project ${desiredProject.name}`);
    state = await readState(config);
    if (state.projects.length !== 1) throw new Error("created project was not readable");
  } else if (!matchesRepresentation(state.projects[0], desiredProject)) {
    await api(
      config,
      "PUT",
      `/management/v1/projects/${state.projects[0].id}`,
      { ...desiredProject },
      [200, 204],
    );
    applied(`updated project ${desiredProject.name}`);
  }

  const projectId = state.projects[0].id;

  for (const role of desiredRoles) {
    if ((state.rolesByKey.get(role.key)?.length ?? 0) === 0) {
      await api(
        config,
        "POST",
        `/management/v1/projects/${projectId}/roles`,
        { roleKey: role.key, displayName: role.key, group: role.group },
        [200, 201],
      );
      applied(`created project role ${role.key}`);
    }
  }

  for (const desired of desiredApps) {
    const rows = state.appsByName.get(desired.name) ?? [];
    const { name, ...oidc } = desired;
    if (rows.length === 0) {
      await api(config, "POST", `/management/v1/projects/${projectId}/apps/oidc`, { name, ...oidc }, [200, 201]);
      applied(`created app ${desired.name}`);
    } else if (!matchesRepresentation(rows[0].oidcConfig ?? {}, oidc)) {
      await api(
        config,
        "PUT",
        `/management/v1/projects/${projectId}/apps/${rows[0].id}/oidc_config`,
        { ...oidc },
        [200, 204],
      );
      applied(`updated app ${desired.name}`);
    }
  }
}

async function main() {
  const config = configuration();
  await authenticate(config);
  let state = await readState(config);
  if (config.mode === "apply") {
    await apply(config, state);
    state = await readState(config);
  }
  const drift = driftFor(state);
  if (drift.length > 0) {
    process.stderr.write(`project drift (${drift.length}):\n- ${drift.join("\n- ")}\n`);
    process.exitCode = 2;
    return;
  }
  const project = state.projects[0];
  process.stdout.write(`project ${config.projectName} auth contract is reconciled (${config.mode})\n`);
  process.stdout.write(`project id (API audience): ${project.id}\n`);
  for (const desired of desiredApps) {
    const app = state.appsByName.get(desired.name)?.[0];
    if (app?.oidcConfig?.clientId) {
      process.stdout.write(`client id ${desired.name}: ${app.oidcConfig.clientId}\n`);
    }
  }
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : "unknown failure";
  process.stderr.write(`reconcile failed: ${message}\n`);
  process.exitCode = 1;
});
