/**
 * Pod-side session-name beacon for remote-TUI sessions.
 *
 * RPC sessions already carry `session_info_changed` over their structured channel. A remote
 * TUI has only PTY bytes, so this module writes the same information as a private OSC that the
 * launcher strips before forwarding output to the user's terminal:
 *
 *   ESC ] 7778 ; n=<base64url UTF-8 name> BEL
 *
 * Base64url keeps arbitrary Unicode names out of the terminal-control grammar. The beacon is
 * TUI-only and best-effort: naming must never interfere with the Pi session itself.
 */

/** Private OSC introducer shared with the launcher-side filter. */
export const SESSION_NAME_BEACON_OSC_PREFIX = "\x1b]7778;n=";

/** Module-scope source composed into every generated remote-TUI extension. */
export function buildSessionNameBeaconSource(): string {
  return `function installPiPodSessionNameBeacon(pi) {
  const emitName = (name) => {
    if (typeof name !== "string" || name.length === 0) return;
    try {
      const encoded = Buffer.from(name, "utf8").toString("base64url");
      process.stdout.write("\\x1b]7778;n=" + encoded + "\\x07");
    } catch {
      // A pod label is a nicety; never let its transport affect the session.
    }
  };

  // session_start covers a named session resumed by a new launcher. The change event covers
  // automatic naming, /name, and session switches inside the same Pi process.
  pi.on("session_start", () => emitName(pi.getSessionName()));
  pi.on("session_info_changed", (event) => emitName(event.name));
}
`;
}

/** Standalone form retained for focused executable tests. */
export function buildSessionNameBeaconExtension(): string {
  return `// pi-pod session-name beacon — generated by pi-pod; do not edit
${buildSessionNameBeaconSource()}
export default function piPodSessionNameBeacon(pi) {
  installPiPodSessionNameBeacon(pi);
}
`;
}
